== Exigences - Généralités

=== Cahier des charges

Le cahier des charges est le document décrivant le périmètre et le contenu du projet.
Il présente... 

* les objectifs que doit atteindre la solution
* les exigences que doit satisfaire la solution
* les exigences en terme de gestion de projet

Il est un outil

* de dialogue entre les MOA, MOE et autres parties prenantes
* de prévention des risques

[%step]
NOTE: Il est en général le document fourni par la MOA. Il peut être la ressource permettant à des prestataires de se positionner sur un appel d'offre.

[%step]
WARNING: Selon l'expérience de la MOA, le cahier des charges peut être plus ou moins précis, plus ou moins clair, plus ou moins détaillé.

[%step]
CAUTION: Un cahier des charges est amené à changer au cours du projet.

=== Cahier de recette

* Le cahier de recette regroupe l'ensemble des tests qui devront être déroulés avant la livraison du produit.
** tests « d’acceptation »
** en agile la recette (ou réception) est incrémentale.
* Le cahier de recette s'appuie sur la description des exigences du cahier des charges.
* Le cahier de recette est à réaliser au plus tôt
* Pour aller plus loin : http://www.test-recette.fr/ 

=== Définition

Exigence _(Source : IEEE)_:: Condition ou capacité que doit présenter un système pour satisfaire un contrat, un standard, une spécification ou tout autre document formel imposé.

[NOTE]
====
- Les exigences sont construites à partir du besoin exprimé par la MOA.
- Cette définition correspond à la notion d'exigence "produit" car elle permettent de spécifier le système ou produit à concevoir. 
====


=== Classification des exigences "produit" 

Le diagramme suivant synthétise une manière consensuelle de classer les exigences produit.
Le diagramme n'est pas exhaustif en termes de sous-classes.

[plantuml,target="exigence-produit", ]
....
@startuml
Exigence_produit <|-- Exigence_fonctionnelle
Exigence_produit <|-- Exigence_non_fonctionnelle
Exigence_non_fonctionnelle <|-- Exigence_technique
Exigence_non_fonctionnelle <|-- Exigence_qualite_code_source
Exigence_non_fonctionnelle <|-- Exigence_sécurité
Exigence_non_fonctionnelle <|-- Exigence_robustesse
Exigence_non_fonctionnelle <|-- Exigence_utilisabilité
Exigence_non_fonctionnelle <|-- Contrainte_technique
Exigence_non_fonctionnelle <|-- Contrainte_réglementaire
Exigence_non_fonctionnelle <|-- Autre_type_exigence
@enduml
....


[NOTE, %step]
==== 
* les exigences fonctionnelles permettent de décrire ce que doit permettre de faire la solution : le quoi.
* les exigences non fonctionnelles décrivent en général les attentes "qualité" de la solution.
* le travail associé à une exigence non fonctionnelle, est en général à remobiliser partiellement ou totalement à chaque fois que le système évolue fonctionnellement.
** Exemple : à chaque nouvelle fonctionnalité, il faut s'assurer que le système reste utilisable, que le nouveau code est testé, etc.
====

===  Classification des exigences "projet"

La MOA peut exprimer aussi des exigences sur la manière de réaliser le système ou le produit. On parle alors d'exigences "projet".

[plantuml,target="exigence-projet"]
....
@startuml
Exigence_projet <|-- Exigence_méthode
Exigence_projet <|-- Exigence_outil
Exigence_projet <|-- Autre_type_exigence
@enduml
....

=== Exercice

Assignez des exigences à leur type.
