== The big picture first ou *l'analyse métier*

Dans le cadre de ce cours, nous allons nous concentrer sur l'*analyse des exigences* qui s'inscrit dans une discipline plus large qu'on nomme l'*analyse métier*.


=== Définition 

L'analyse métier:: L'analyse métier (_business analysis_ en anglais) est une discipline professionnelle qui consiste à identifier les besoins métier d'une entreprise ou d'une organisation et à déterminer des solutions à ses problèmes. Les solutions comprennent souvent une composante de développement de systèmes logiciels, mais peuvent aussi consister en des améliorations de processus, des changements organisationnels ou une planification stratégique et l'élaboration de politiques. La personne qui s'acquitte de cette tâche est appelée un analyste métier (_business analyst_ en anglais) footnote:["Business Analysis Body of Knowledge v2.0". International Institute of Business Analysis.].

[%step]
IMPORTANT: L'analyse métier est composées de plusieurs sous-disciplines chacune mobilisant des méthodes et outils propres.


=== Analyse d'entreprise ou d'organisation

S'attache à comprendre les besoins de l'entreprise dans son ensemble, son orientation stratégique, et à identifier les initiatives qui permettront à une entreprise d'atteindre ces objectifs stratégiques. Elle comprend également :

[%step]
- La création et la maintenance de l'architecture métier de l'entreprise
- la réalisation d'études de faisabilité
- l'identification de nouvelles opportunités commerciales
- le cadrage et la définition de nouvelles opportunités commerciales
- la préparation de l'analyse de rentabilité
- réalisation de l'évaluation initiale des risques


=== Élicitation des exigences 

Mise en œuvre de techniques pour l'explicitation et la collecte des exigences des différentes parties-prenantes dans un projet.


ifdef::backend-revealjs[=== !]

Exigence _(Source : IEEE)_:: Condition ou capacité que doit présenter un système pour satisfaire un contrat, un standard, une spécification ou tout autre document formel imposé.



ifdef::backend-revealjs[=== !]

Les techniques d'éliciation des exigences comprennent (liste non exhaustive) :

[%step]
- Brainstorming
- Focus groupes
- Interviews/questionnaires
- Sondages
- Analyse des tâches utilisateurs
- Observation du poste de travail
- Design thinking

=== Analyse et documentation des exigences

Mise en œuvre de techniques permettant de décrire de manière suffisament détaillée les exigences de telle sorte qu'elles puissent être implémentées par une équipe de développement.

[%step]
IMPORTANT: C'est cette sous-discipline qui nous intéresse principalement dans le contexte de cette _ressource_. Nous l'aborderons principalement dans le contexte de méthodes agiles.


ifdef::backend-revealjs[=== !]

==== Analyse des exigences

Les principales formes d'analyse sont les suivantes :

[%step]
- Analyse des processus métier
- Analyse orientée objet
- etc.


ifdef::backend-revealjs[=== !]

==== Documentation

La documentation des exigences peut prendre plusieurs formes :

[%step]
- Textuelle - par exemple, des histoires qui résument des informations spécifiques.
- Matrice - par exemple, un tableau des exigences avec les priorités.
- Diagrammes - par exemple, comment les données circulent d'une structure à l'autre.
- etc.

=== Planification et gestion des exigences

Planification du développement des exigences, définition des priorités et gestion des changements.


=== Communication des exigences

Mobilise les techniques permettant de s'assurer que les parties prenantes ont une compréhension commune des exigences et de la manière dont elles seront mises en œuvre.


=== Vérification et validation de la solution

Mis en œuvre des méthodes et techniques permettant la vérification et la validation d'une solution proposée.

[%step]
Vérification:: « Confirmation par des preuves tangibles que les exigences spécifiées ont été satisfaites »

[%step]
Vérifier, c’est répondre à la question : « Faisons- nous le produit correctement ? »

[%step]
Validation:: « Confirmation par des preuves tangibles que les exigences pour une utilisation spécifique ou une application prévue ont été satisfaites »

[%step]
Valider, c’est répondre à la question : « Faisons- nous le bon produit ? »

_(Source : Norme ISO 9000 : 2000)_




